name: solar-system

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - feature/*

jobs:
    unit-testing:
        name: unit testing
        strategy:
            matrix:
                nodejs_version: [18,19,20]
                operating_systems: [ubuntu-latest, macos-latest]
                # target: [1,2,3]
                exclude:
                    - nodejs_version: 18
                      operating_systems: macos-latest

        runs-on: ${{ matrix.operating_systems }}
        steps:
            - name: checkout repo
              uses: actions/checkout@v3
              
            - name: setup nodejs version ${{ matrix.nodejs_version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.nodejs_version }}

            - name: install dependencies
              run: npm install

            - name: unit test  
              run: |
                echo "${{ vars.MONGO_USERNAME }}" > data-${{ matrix.operating_systems }}-${{ matrix.nodejs_version }}.txt
                echo ${{ matrix.operating_systems }}-${{ matrix.nodejs_version }}
                ls
                pwd
                cat data-${{ matrix.operating_systems }}-${{ matrix.nodejs_version }}.txt
            
            - name: upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: test-binary-${{ matrix.operating_systems }}-${{ matrix.nodejs_version }}
                path: data-${{ matrix.operating_systems }}-${{ matrix.nodejs_version }}.txt
                retention-days: 3
    code-coverage:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v3
              
            - name: setup nodejs version ${{ matrix.nodejs_version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.nodejs_version }}
                
            - name: cache npm dependencies
              uses: actions/cache@v3
              with:
                path: node_modules
                key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
                

            - name: install dependencies
              run: npm install

            - name: code-coverage 
              continue-on-error: true
              run: npm run coverage
                            
            - name: upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: coverage-binary
                path: coverage
                retention-days: 3
    docker:
      name: containerization
      needs: [unit-testing, code-coverage]
      runs-on: ubuntu-latest
      steps:
        - name: checkout-repo
          uses: actions/checkout@v4
        
        - name: Dockerhub-login
          uses: docker/login-action@v2.2.0
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: #{{ secrets.DOCKERHUB_PASSWORD }}



