name: solar-system

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - feature/*

jobs:
    unit-testing:
        name: unit testing
        strategy:
            matrix:
                nodejs_version: [18,19,20]
                operating_systems: [ubuntu-latest, macos-latest]
                # target: [1,2,3]
                exclude:
                    - nodejs_version: 18
                      operating_systems: macos-latest

        runs-on: ${{ matrix.operating_systems }}
        steps:
            - name: checkout repo
              uses: actions/checkout@v3
              
            - name: setup nodejs version ${{ matrix.nodejs_version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.nodejs_version }}

            - name: install dependencies
              run: npm install

            - name: unit test  
              run: |
                echo "${{ vars.MONGO_USERNAME }}" > data-${{ matrix.operating_systems }}-${{ matrix.nodejs_version }}.txt
                echo ${{ matrix.operating_systems }}-${{ matrix.nodejs_version }}
                ls
                pwd
                cat data-${{ matrix.operating_systems }}-${{ matrix.nodejs_version }}.txt
            
            - name: upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: test-binary-${{ matrix.operating_systems }}-${{ matrix.nodejs_version }}
                path: data-${{ matrix.operating_systems }}-${{ matrix.nodejs_version }}.txt
                retention-days: 3



