name: solar-system

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - feature/*

jobs:
    unit-testing:
        name: unit testing
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v3
              
            - name: setup nodejs version 18
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: install dependencies
              run: npm install

            - name: unit test
              run: |
                echo "${{ vars.MONGO_USERNAME }}" > data.txt
                ls
                pwd
                cat data.txt
            
            - name: upload artifacts
              uses: actions/upload-artifact@v3
              with:
                name: test-binary
                path: data.txt



